"""Report domain entity — final output of the processing pipeline."""

from datetime import datetime, timezone
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Report(BaseModel):
    """Final structured report for a processed audio job.

    Generated by ReportWorker. Contains analysis summary formatted
    for display in frontend and export.
    """

    model_config = {"frozen": False}

    id: UUID = Field(default_factory=uuid4)
    job_id: UUID = Field(..., description="Parent AudioJob ID")
    analysis_id: UUID = Field(..., description="Source Analysis ID")
    transcript_id: UUID = Field(..., description="Source Transcript ID")

    title: str = Field(..., description="Auto-generated report title")
    storage_path: str | None = Field(
        default=None, description="Object storage path for PDF export"
    )

    # Denormalized summary fields for fast dashboard display
    overall_score: float = Field(
        ..., ge=0.0, le=10.0, description="Weighted overall performance score"
    )
    call_duration_seconds: float = Field(..., gt=0.0)
    compliance_passed: bool = Field(...)
    agent_sentiment: str = Field(...)
    customer_sentiment: str = Field(...)
    summary: str = Field(...)

    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
